### ISSUE TITLE
Implement missing abstract methods in TextLedger

### ISSUE THREAD

**Issue by lasuk** [macxred/pyledger#11]
**Tasks**

- Add a property to `TextLedger` to hold the default file path for ledger and price entries.
- Identify all abstract methods in the `LedgerEngine` class that are not currently implemented in `TextLedger`.
- Implement these methods in `TextLedger`.

**Integration into pyledger Architecture**

TextLedger stores ledger, and price data in multiple files, not in a single file. Adding ledger and price entries therefore requires an additional 'file' argument with the file path. This argument is not available in the abstract LedgerEngine method definition, which complicates the integration with the abstract class. We can work around the problem by setting a default file path as a property in TextLedger and using this default if no specific storage location is provided.

**Comment by AlexTheWizardL** [comment]
### **Workflow for TextLedger**

#### **Objective**
To establish a consistent, human-readable, and traceable CSV format for storing entities, with additional accessor and mutator methods to manage adding, modifying, and deleting entities while ensuring that files have as few changes as possible to make it easy to identify modifications via git. **This is an example for one entity, the ledger, and will later be applied to the rest of the entities.**

---

### **Step 1: `prepare_df_for_storing()`** – Standardizing the DataFrame
This method ensures that the DataFrame is standardized before being saved to a CSV. It includes column reordering, renaming if needed, rounding of floating-point values, and multi-level sorting.

**Code Snippet**:

```python
import pandas as pd
from typing import List, Dict

def prepare_df_for_storing(
    df: pd.DataFrame,
    columns_order: List[str],
    col_names: Dict[str, str] = None,
    digits: float = 0.01,
    sort_by: List[str] = None
) -> pd.DataFrame:
    """
    Standardizes the DataFrame by setting a common structure before converting it to CSV.

    Args:
        df: The DataFrame to prepare.
        columns_order: List of columns in the desired order.
        col_names: Optional dictionary to rename columns.
        digits: The precision for rounding floats (default is 0.01).
        sort_by: List of columns to sort by. Supports multi-level sorting.

    Returns:
        pd.DataFrame: The standardized DataFrame ready for saving.
    """
    
    # Rename columns if col_names is provided
    if col_names:
        df = df.rename(columns=col_names)
    
    # Reorder columns based on columns_order
    df = df[columns_order]
    
    # Round numeric columns to the specified digits
    df = df.round({col: digits for col in df.select_dtypes(include=['float64']).columns})
    
    # Sort the DataFrame by the specified columns (multi-level sorting)
    if sort_by:
        df = df.sort_values(by=sort_by)
    
    return df
```

---

### **Step 2: `write_fixed_width_csv()`** – Generating Human-Readable CSV
This method converts the prepared DataFrame into a human-readable CSV with fixed-width columns and right-aligned text, ensuring readability by controlling column width.

**Code Snippet**:

```python
import pandas as pd
import numpy as np

def write_fixed_width_csv(
    df: pd.DataFrame,
    path: str = None,
    sep: str = ", ",
    na_rep: str = "",
    n: int = None,
    *args,
    **kwargs
) -> str:
    """
    Generate a human-readable CSV with fixed-width columns.

    Args:
        df (pd.DataFrame): DataFrame to be written to CSV.
        path: Name/path of the CSV file to write. If None, returns the CSV output as a string.
        sep: Separator for the CSV file, default is ', '. Multi-char separators are supported.
        na_rep: String representation for NA/NaN data. Default is ''.
        n: Number of columns from the start to have fixed width. If None, applies to all columns except the last.
        *args: Additional arguments for pandas to_csv method.
        **kwargs: Additional keyword arguments for pandas to_csv method.

    Returns:
        str: CSV output as a string if the path is None.
    """
    result = {}
    fixed_width_cols = df.shape[1] - 1 if n is None else n

    for i, colname in enumerate(df.columns):
        col = df.iloc[:, i]
        col_str = pd.Series(np.where(col.isna(), na_rep, col.astype(str)))
        
        # Calculate max length for fixed width
        max_length = max(col_str.dropna().apply(len).max(), len(colname))

        # Right-align text for fixed-width columns
        if i < fixed_width_cols:
            col_str = col_str.apply(lambda x, ml=max_length: x.rjust(ml))
            colname = colname.rjust(max_length)

        # Add separator to all but the first column
        if i > 0:
            col_str = sep[1:] + col_str
            colname = sep[1:] + colname

        result[colname] = col_str

    result = pd.DataFrame(result)

    # Write to CSV
    return result.to_csv(path, sep=sep[0], index=False, na_rep=na_rep, *args, **kwargs) if path else result.to_csv(index=False, sep=sep[0], na_rep=na_rep, *args, **kwargs)
```

---

### **Step 3: `save_ledger()`** – Finalizing and Saving the Ledger
This method processes the DataFrame (handling ID or date manipulations specific to ledger entries) before calling `prepare_df_for_storing()` and passing it to `write_fixed_width_csv()` to save the final CSV.

**Code Snippet**:

```python
def save_ledger(df: pd.DataFrame, path: str) -> None:
    """
    Prepares and saves the ledger DataFrame to a CSV file.
    
    Args:
        df: The ledger DataFrame to save.
        path: The path where the CSV file should be saved.
    """
    # Define the common structure and order for columns
    columns_order = ["date", "account", "counter_account", "currency", "amount", "base_currency_amount", "vat_code", "text", "document"]
    
    # Optionally, rename columns if necessary
    col_names = {
        # Add any column renaming logic here
    }
    
    # Prepare DataFrame for storing
    prepared_df = prepare_df_for_storing(df, columns_order, col_names, sort_by=['date', 'account', 'amount'])
    
    # Save to CSV with consistent formatting
    write_fixed_width_csv(prepared_df, path)
```

---

### **Key Benefits**

- **Consistency**: Every CSV entity follows a standardized structure, improving human readability and maintaining uniformity across entries.
  
- **Multi-Level Sorting**: By supporting multi-level sorting (e.g., sorting first by `date`, then `account`, and finally `amount`), we prevent data inconsistencies and ensure a predictable row order. This approach minimizes unnecessary changes, making it easier to track modifications via git.
  
- **Flexibility**: Customizable options for column renaming, rounding precision, and sorting ensure adaptability to various entities while maintaining consistent output.

---

### **Accessor and Mutator Methods for TextLedger**

These methods handle adding, modifying, and deleting entries from the ledger, using `ledger()` to read the CSV at the beginning, applying the corresponding logic, and saving the changes with `save_ledger()` at the end.

#### **Accessor: `ledger()`**

This method reads the CSV file from the default or provided path and returns a standardized DataFrame using `standardize_ledger()`.

**Code Snippet**:

```python
class TextLedger:
    default_ledger_path = "default/path/to/ledger.csv"  # Default ledger path

    def ledger(self, path: str = default_ledger_path) -> pd.DataFrame:
        """
        Reads the CSV from the given path or the default class-level path and returns a standardized DataFrame.
        
        Args:
            path: Path to the ledger CSV file. Defaults to the class property default_ledger_path.
        
        Returns:
            pd.DataFrame: The standardized ledger DataFrame.
        """
        # Read the CSV into a DataFrame
        df = pd.read_csv(path)
        
        # Standardize the DataFrame using standardize_ledger()
        standardized_df = standardize_ledger(df)
        
        return standardized_df
```

#### **Mutators: `add_ledger()`, `modify_ledger()`, `delete_ledger()`**

These methods handle adding, modifying, and deleting ledger entries by reading the current ledger, applying the relevant logic from `MemoryLedger`, and saving the updated DataFrame back to the CSV file.

**`add_ledger()` – Adding a Ledger Entry:**

```python
def add_ledger(self, new_entry: pd.DataFrame, path: str = default_ledger_path) -> None:
    """
    Adds a new ledger entry to the CSV file.
    Use logic from memory_ledger.
    """
    # Read the existing ledger
    df = self.ledger(path)
    
    # Use logic from memory_ledger to modify df
    
    # Save the updated ledger back to the CSV file
    save_ledger(df, path)
```

**`modify_ledger()` – Modifying a Ledger Entry:**

```python
def modify_ledger(self, modified_entry: pd.DataFrame, condition: dict, path: str = default_ledger_path) -> None:
    """
    Modifies an existing ledger entry in the CSV file.
    Use logic from memory_ledger.
    """
    # Read the existing ledger
    df = self.ledger(path)
    
    # Use logic from memory_ledger to modify df
    
    # Save the modified ledger back to the CSV file
    save_ledger(df, path)
```

**`delete_ledger()` – Deleting a Ledger Entry:**

```python
def delete_ledger(self, condition: dict, path: str = default_ledger_path) -> None:
    """
    Deletes a ledger entry from the CSV file.
    Use logic from memory_ledger.
    """
    # Read the existing ledger
    df = self.ledger(path)
    
    # Use logic from memory_ledger to modify df
    
    # Save the updated

 ledger back to the CSV file
    save_ledger(df, path)
```

---

### **Conclusion**

This complete workflow covers the consistent CSV handling for TextLedger, including the standardized reading and writing of CSV files. It also integrates the accessor (`ledger()`) and mutator methods (`add_ledger()`, `modify_ledger()`, `delete_ledger()`), ensuring a reusable and consistent process for managing ledger entries.

This approach is designed to minimize unnecessary changes in files, making it easier to track modifications via git, while maintaining consistency and flexibility.

**Comment by AlexTheWizardL** [comment]
### **Part 1: Column Schema Flow**

1. **Goal**:
   - Improve the DataFrame column schema by defining:
     - Data type (dtype)
     - Required columns
     - Columns order
     - Column names
     - Sorting for consistent row order across entities.

2. **Motivation**:
   - Enforcing a consistent schema for all entities ensures that the structure of the DataFrame remains the same, allowing for smooth handling of data between different operations and ensuring correct processing of all entries.

3. **Responsibilities**:
   - **Lukas** will:
     - Provide the new columns combining optional and required fields.
     - Define better column names.
     - Set the new order of columns along with the default sorting field for each entity.
   - **Alex** will:
     - Update the code base according to the schema updates.
     - Ensure proper handling of new cases based on the updated schema.

---

### **Part 2: Ledger System Flow**

1. **Initialization (`__init__`)**:
   - Initializes the system with a root path and a cache timeout.
   - Sets up caching for ledger data.

   **Motivation**: Organizing all ledger files within a root path ensures that operations are scoped to this location. Caching improves efficiency by reducing redundant reads from the filesystem.

2. **Caching**:
   - **`_is_expired()`**: Checks if the cache has expired based on the defined timeout.
   - **`invalidate_ledger_cache()`**: Invalidates the ledger cache after any modification to ensure consistency.
   - **`read_ledger()`**: Reads all ledger data from CSV files, caches it, and standardizes it.

   **Motivation**: Caching minimizes unnecessary disk reads, which improves the performance of ledger operations. By defining expiration and cache invalidation, we ensure that stale data isn't used, while improving performance through data reuse.

---

### **Part 3: Mutators and File Management**

**Mutators** manage adding, modifying, and deleting ledger entries using the `file_path` column to track the source file for each row. This column ensures that only the necessary files are updated or rewritten when changes occur.

- **Efficiency**: The `file_path` column allows mutators to update only the required files, avoiding unnecessary rewrites across the entire ledger system.
- **Data Integrity**: Each entry must have a unique `id` and an associated `file_path`, ensuring well-defined operations that are predictable and reliable.
- **Modular Saving**: The `save_ledger()` function groups data by `file_path`, ensuring that only the affected files are saved, optimizing performance.

---

### **Part 4: Saving and Standardizing**

1. **Saving**:
   - **`save_ledger()`**: 
     - Handles saving the ledger DataFrame. It groups rows by their `file_path` and ensures that only the necessary files are written. The files are saved in a parent-child order, ensuring that directories are created before files are written.
     - The `file_path` column is used to determine where each group of rows is saved, and the parent directories are automatically created if they don't exist.
   
   - **`save_fixed_csv()`**: 
     - Saves the DataFrame in a fixed-width CSV format, ensuring consistency and human readability. The `file_path` column is dropped before saving, so it does not appear in the final output file.

   **Motivation**: 
   - By grouping rows by `file_path`, the `save_ledger()` function ensures that only the required files are written, reducing unnecessary writes. Sorting by the parent-child hierarchy guarantees that directories are created in the correct order, preventing any issues when saving files. 
   - The `save_fixed_csv()` method ensures that the data is saved in a consistent, human-readable format, which is useful for tracking changes through version control systems like Git.

---

### **Full Code for Ledger System**

**Note**: The following code is for demonstrating the common flow and may contain simplified logic or minor lacks, focusing on illustrating the overall architecture.

```python
import pandas as pd
from pathlib import Path
from typing import Optional, Union, List
from datetime import datetime


class LedgerSystem:
    def __init__(self, root_path: str, cache_timeout: int = 300):
        """
        Initializes the LedgerSystem with the root path and cache timeout.
        
        Args:
            root_path (str): The root path where all entities will be stored.
            cache_timeout (int): The cache timeout in seconds.
        """
        self.root_path = Path(root_path)
        self._cache_timeout = cache_timeout
        self._ledger_cache: Optional[pd.DataFrame] = None
        self._ledger_cache_time: Optional[datetime] = None

    def read_ledger(self) -> pd.DataFrame:
        """
        Reads all CSV files from the 'ledger' folder. Adds the file path to each DataFrame row.
        Returns a combined DataFrame of all ledger data, including the 'file_path' column.
        """
        if self._ledger_cache is not None and not self._is_expired(self._ledger_cache_time):
            return self._ledger_cache

        ledger_folder = self.root_path / 'ledger'
        ledger_files = list(ledger_folder.rglob('*.csv'))

        dataframes = []
        for file in ledger_files:
            df = pd.read_csv(file)
            file_path = str(file.relative_to(self.root_path))
            
            # Append file path to each row
            df['file_path'] = file_path
            dataframes.append(df)

        if dataframes:
            combined_df = pd.concat(dataframes, ignore_index=True)
            self._ledger_cache = self.standardize_ledger(combined_df)
        else:
            self._ledger_cache = pd.DataFrame(columns=['id', 'file_path'])  # Empty DataFrame if no files

        self._ledger_cache_time = datetime.now()
        return self._ledger_cache

    def add_ledger_entry(self, entry: pd.DataFrame) -> int:
        """
        Adds a new ledger entry. Uses 'file_path' to identify where to write the entry.
        """
        entry = self.standardize_ledger(entry)
        if entry["id"].nunique() != 1:
            raise ValueError("Id must be unique across all rows.")
        
        ledger_id = entry["id"].iat[0]
        df = self.read_ledger()

        if (df["id"] == ledger_id).any():
            raise ValueError(f"Ledger entry with id '{ledger_id}' already exists.")

        # Check if file_path is provided
        if "file_path" not in entry.columns or entry["file_path"].nunique() != 1:
            raise ValueError("Each entry must have a unique 'file_path'.")

        file_path = entry["file_path"].iat[0]
        updated_ledger = pd.concat([df, entry])
        updated_ledger = self.standardize_ledger(updated_ledger)

        # Write only the affected file using save_ledger() and save_fixed_csv()
        self.save_ledger(updated_ledger[updated_ledger["file_path"] == file_path])
        self.invalidate_ledger_cache()
        return ledger_id

    def modify_ledger_entry(self, entry: pd.DataFrame) -> None:
        """
        Modifies an existing ledger entry. Uses 'file_path' to identify where to write the entry.
        """
        entry = self.standardize_ledger(entry)
        if entry["id"].nunique() != 1:
            raise ValueError("Id must be unique across all rows.")

        ledger_id = str(entry["id"].iat[0])
        df = self.read_ledger()

        if ledger_id not in df["id"].values:
            raise ValueError(f"Ledger entry with id '{ledger_id}' not found.")

        # Check if file_path is provided
        if "file_path" not in entry.columns or entry["file_path"].nunique() != 1:
            raise ValueError("Each entry must have a unique 'file_path'.")

        file_path = entry["file_path"].iat[0]
        updated_ledger = pd.concat([df[df["id"] != ledger_id], entry])
        updated_ledger = self.standardize_ledger(updated_ledger)

        # Write only the affected file using save_ledger() and save_fixed_csv()
        self.save_ledger(updated_ledger[updated_ledger["file_path"] == file_path])
        self.invalidate_ledger_cache()

    def delete_ledger_entry(self, ids: Union[str, List[str]], allow_missing: bool = False) -> None:
        """
        Deletes ledger entries by 'id'. Uses 'file_path' to identify the files to update.
        """
        if isinstance(ids, str):
            ids = [ids]

        df = self.read_ledger()

        if not allow_missing:
            missing_ids = set(ids) - set(df["id"])
            if missing_ids:
                raise KeyError(f"Entries with ids '{', '.join(missing_ids)}' not found.")

        # Find affected file paths
        affected_files = df[df["id"].isin(ids)]["file_path"].unique()

        # Update only affected files
        updated_ledger = df[~df["id"].isin(ids)]
        updated_ledger = self.standardize_ledger(updated_ledger)

        for file_path in affected_files:
            self.save_ledger(updated_ledger[updated_ledger["file_path"] == file_path])

        self.invalidate_ledger_cache()

    def save_ledger(self, df: pd.DataFrame) -> None:
        """
        Saves the ledger DataFrame to the corresponding CSV file. Groups rows by 'file_path'
        and writes only the necessary files.
        
        Args:
            df (pd.DataFrame): The DataFrame with an 'id' and 'file_path' column.
        """
        # Group by file path to save only the necessary files
        grouped = df.groupby('file_path')

        # Sort file paths by parent-child relationships before saving
        sorted_file_paths = sorted(grouped.groups.keys(), key=lambda p: Path(p).parts)

        for file_path in sorted_file_paths:
            group_df = grouped.get_group(file_path)
            full_path = self.root_path / file_path

            # Ensure the parent directories exist
            full_path.parent.mkdir(parents=True, exist_ok=True)

            # Save the file with fixed-width CSV formatting
            self.save_fixed_csv(group_df, full_path)

    def save_fixed_csv(self, df: pd.DataFrame, path: Path) -> None:
        """
        Saves the ledger DataFrame as a fixed-width CSV file.
        
        Args:
            df (pd.DataFrame): The DataFrame to save.
            path (Path): The file path where the data should be saved.
        """
        df.drop(columns=['file_path'], inplace=True)  # Drop 'file_path' column before saving
        df.to_csv(path, index=False)  # Save to CSV without 'file_path'

    def _is_expired(self, cache_time: Optional[datetime]) -> bool:
        """
        Checks if the cache has expired based on the cache timeout.
        
        Args:
            cache_time (datetime | None): The timestamp when the cache was last updated.
        
        Returns:
            bool: True if the cache is expired or cache_time is None, False otherwise.
        """
        if cache_time is None:
            return True
        return (datetime.now() - cache_time).total_seconds() > self._cache_timeout

    def invalidate_ledger_cache(self) -> None:
        """
        Invalidates the cached ledger data.
        """
        self._ledger_cache = None
        self._ledger_cache_time = None
```

**Comment by AlexTheWizardL** [comment]
## Left to do with a TextLedger:

### **Settings**

#### **Getter, Setter**
Currently, settings are stored in the `StandaloneLedger` component as a private property `_settings`, and are accessed directly without using `@property` methods. It would be straightforward to define a getter and setter for `settings` within `StandaloneLedger`. This change would slightly improve the architecture and provide an opportunity to implement reading settings from a file when the getter is triggered and saving them when the setter is triggered. The current architecture does not allow for this functionality.

#### **Mechanism for Storing within `.yml` File**
We agreed to store settings in a `.yml` file, which is a common practice. For this, it would be practical to implement `read_settings` and `write_settings_file` methods. Since there is no need for precise git diffs for settings, these methods can be kept simple, handling the reading and writing of a `settings.yml` file within `self.root_directory`.

#### **Caching**
A caching mechanism would be useful, similar to the one implemented for the ledger entity. This would help avoid unnecessary reads and writes to the settings file, improving performance.

**Code Snippet:**

```python
def write_dict_to_yml(data: dict, file_path: str):
    """Save a dictionary to a .yml file.

    Args:
        data (dict): The dictionary to be saved.
        file_path (str): The path to the .yml file where the dictionary will be saved.
    """
    with open(file_path, "w") as file:
        yaml.dump(data, file, default_flow_style=False)


def read_dict_from_yml(file_path: str) -> dict:
    """Load a dictionary from a .yml file.

    Args:
        file_path (str): The path to the .yml file to be read.

    Returns:
        dict: The dictionary read from the .yml file.
    """
    with open(file_path, "r") as file:
        return yaml.safe_load(file)
```

### **Questions**
There are a few options for where to place the `read_dict_from_yml` and `write_dict_to_yml` methods:

- Add them as `staticmethods` in the `TextLedger` class.
- Place them in the `helpers.py` file for reuse across multiple classes.
- Incorporate the reading and writing directly within the getter and setter for the `settings` property.

Additionally, `settings` are currently required by the `__init__()` method, and we already have a constant for them. Here are the key questions to consider:

- Should predefined settings be passed as a constant to the `TextLedger` class? If not, should we just initialize `_settings` as an empty dictionary?
- If no `_settings` are passed during initialization, should we store an empty dictionary or return some default values?

---

### **Implement Same Approach as for Ledger Entity to Accounts and Tax Codes**

#### **File Structure:**
For accounts and tax codes, there is no need to create multiple files within nested directories. We agreed to have only one file for tax codes and one for accounts, both stored within `self.root_directory`.

#### **Read/Write Logic:**
This logic will be simpler than for the ledger entity, but it will follow the same main principles. Here are the code snippets:

```python
def read_tax_codes(self) -> pd.DataFrame:
    """Read tax codes from CSV file in the root directory.

    Returns:
        pd.DataFrame: A DataFrame following the TAX_CODE_SCHEMA.
    """

    try:
        tax_codes = pd.read_csv(self.root_path / "tax_codes.csv", skipinitialspace=True)
        # TODO: remove line once old systems are migrated
        tax_codes.rename(columns=TAX_CODE_COLUMN_SHORTCUTS, inplace=True)
        tax_codes = self.standardize_tax_codes(tax_codes)
    except Exception as e:
        tax_codes = self.standardize_tax_codes(None)
        self._logger.warning(f"Error trying to read tax codes file: {e}")
    return tax_codes.copy()

@classmethod
def write_tax_codes_file(cls, df: pd.DataFrame, path: Path):
    """Save tax codes to a canonical human-readable CSV file.

    Args:
        df (pd.DataFrame): tax codes to save.
        path (Path): The file path where tax codes will be saved.

    Returns:
        pd.DataFrame: Formatted tax codes DataFrame ready for saving.
    """
    df = enforce_schema(df, TAX_CODE_SCHEMA, sort_columns=True, keep_extra_columns=True)
    optional = TAX_CODE_SCHEMA.loc[~TAX_CODE_SCHEMA["mandatory"], "column"].to_list()
    to_drop = [col for col in optional if df[col].isna().all() and not df.empty]
    df.drop(columns=to_drop, inplace=True)
    n_fixed = TAX_CODE_SCHEMA["column"].isin(df.columns).sum()
    write_fixed_width_csv(df, file=path, n=n_fixed)

    return df
```

#### **Mutator Methods:**
These can largely be copied from the `MemoryLedger`, with a few modifications. Instead of accessing a private property, these methods will use an accessor method to retrieve the data, then call the write file and invalidate methods, rather than assigning directly to a private variable.

Here’s an example:

```python
def add_tax_code(
    self,
    id: str,
    rate: float,
    account: str,
    is_inclusive: bool = True,
    description: str = "",
) -> None:
    tax_codes = self.tax_codes()
    if (tax_codes["id"] == id).any():
        raise ValueError(f"Tax code '{id}' already exists")

    new_tax_code = self.standardize_tax_codes(pd.DataFrame({
        "id": [id],
        "description": [description],
        "account": [account],
        "rate": [rate],
        "is_inclusive": [is_inclusive],
    }))
    tax_codes = pd.concat([tax_codes, new_tax_code])
    self.write_tax_codes_file(tax_codes, self.root_path / "tax_codes.csv")
    self._invalidate_tax_codes()
```
