### ISSUE TITLE
`TextLedger` documentation

### ISSUE THREAD

**Issue by lasuk** [macxred/pyledger#13]
- Add a README section or a separate markdown file documenting the `TextLedger` class and its usage.
- Include examples demonstrating how to use `TextLedger`.
- Explain how TextLedger can be used in conjunction with git and GitHub to version control and accounting system.

**Comment by AlexTheWizardL** [comment]
### Issue: Best Approach for Showing Git Diffs in the README

We’re exploring the most effective way to display Git diffs in our README, particularly for showcasing how `TextLedger` minimizes changes and preserves file structure. Here are the possible ways we could approach this:

---

### 1. **Using Built-In `diff` Syntax in Markdown**

We can use GitHub's built-in `diff` syntax to show Git changes directly in the README. This is straightforward, but note that it doesn’t support inline character-level changes (only whole lines). Here’s an example of how this would look:

```diff
- 4, 2024-05-24, 9991, 9994, USD, 888888.88,        450.45, OutRed, ledger 4,
+ 4, 2024-05-24, 9991, 9994, USD, 788888.88,        450.45, OutRed, ledger 4,
```

#### Pros:
- Native support within Markdown and visible on GitHub.
- Simple and lightweight, with no external assets needed.

#### Cons:
- No inline diff support for specific characters or substrings.
- Entire line changes are shown, making it harder to visually capture small changes.

---

### 2. **Storing Images in the `assets/` Folder**

Another option is to manually capture Git diffs (like the one shown in the screenshot below) and store the images in an `assets/` folder within the repository. We can then reference these images in the README.

#### Pros:
- Captures the full inline diff, with character-level changes highlighted.
- Works well for visual presentation and easily understood by viewers.
  
#### Cons:
- Increases repository size, especially if we have many images.
- Requires manual effort to capture diffs and update them if changes are made.

---

### 3. **Creating a Separate Git Branch and Hosting Images on GitHub**

We can commit the diffs to a separate Git branch and take advantage of GitHub's built-in image hosting (via issues or PR comments). Images hosted by GitHub can be referenced directly in the README.


#### Pros:
- No increase in repository size (images are hosted by GitHub).
- Allows for easy updates and replacements.

#### Cons:
- A bit more complex to manage, especially for keeping track of images across branches or issues.
- Not part of the repository directly, so it adds some indirection.
