### ISSUE TITLE
Replace 'base_currency' by 'reporting_currency'

### ISSUE THREAD

**Issue by lasuk** [macxred/pyledger#30]
**Task:** Replace the term 'base_currency' in our code base by the more commonly used term 'reporting_currency'.

**Motivation:** 
<details><summary>Click to expand ChatGPT thread</summary>
<p>
### User Question

Which term is most common in accounting to designate the currency, in which a company's balance sheet and income statement are stated?

---

### Assistant Response

The most common term used in accounting to designate the currency in which a company's balance sheet and income statement are stated is **"functional currency."**

The **functional currency** refers to the primary currency of the economic environment in which a company operates and conducts its business. It is used to record financial transactions in the financial statements, such as the balance sheet and income statement.

In some contexts, the term **"reporting currency"** may also be used, especially when referring to multinational companies that consolidate financials from multiple subsidiaries operating in different currencies. The reporting currency is the currency in which the parent company presents its consolidated financial statements.

So, **functional currency** and **reporting currency** are the key terms, with functional currency being the primary one.

---

### User Follow-up

How about "main currency" or "base currency"?

---

### Assistant Response

The terms **"main currency"** and **"base currency"** are not commonly used in accounting to refer to the currency in which a company's financial statements are prepared. Instead, these terms are more frequently encountered in contexts such as **foreign exchange trading** or **investment portfolios**.

- **Main currency** is a less formal term and may be used in casual conversation to describe the primary currency a company deals with, but it is not standard in accounting terminology.

- **Base currency** is typically used in foreign exchange markets to refer to the first currency in a currency pair. For example, in the currency pair USD/EUR, the USD is the base currency, and the EUR is the quote currency. It doesn't commonly refer to the currency in which financial statements are prepared.

In formal accounting contexts, **functional currency** and **reporting currency** are the more accurate and standard terms used to describe the currency of a company's financial statements.

</p>
</details>

**Comment by lasuk** [comment]
Let's also implement other name changes at the same time:
- `vat_code` -> `tax_code`

**Comment by lasuk** [comment]
**Proposal:** modify the interface for the dump/restore functionality and to introduce abstract functionality to restore a ledger system from given data frames. 
- rename current `dump` and `restore` to `dump_to_zip` and `restore_from_zip`.
- introduce a new `restore` method that replaces an entire ledger system with data provided as argument (mostly) in the form of data frames 

**Motivation:** 
- This method can be used either in tests (where we hard-code the test data), or from file (where we read input data from a zip archive. It will allow us to define a clean and clear test environment by providing hard-coded data for an entire ledger system.

**Steps:**
- Rename `LedgerEngine.dump()` -> `LedgerEngine.dump_to_zip()`
- Rename `LedgerEngine.restore()` -> `LedgerEngine.restore_from_zip()`
- Drop `MemoryLedger.restore()`
- Introduce new `LedgerEngine.restore()` (see below)
- Refactor `LedgerEngine.restore_from_zip()` to be a thin wrapper around `LedgerEngine.restore()` using a zip archive as input.

**Sketch:**
````
class LedgerEngine(ABC):
    def restore(
        base_currency: str | None = None, 
        vat_codes: pd.DataFrame | None = None, 
        accounts: pd.DataFrame | None = None, 
        ledger: pd.DataFrame | None = None, 
        price: pd.DataFrame | None = None, 
        precision: dict | None = None, 
        fx_adjustment: pd.DataFrame | None = None
    ):
        """
        Replaces the entire ledger system with data provided as arguments.

        Args:
            base_currency str | None: Reporting currency. If `None`, the reporting currency remains unchanged.
            vat_codes pd.DataFrame | None: VAT codes of the restored ledger system. 
                If `None`, VAT codes remains unchanged.
            ...
        """
        if base_currency is not None:
            self.base_currency = base_currency
        if vat_codes is not None:
            self.mirror_vat_codes(vat_codes, delete=True)
        if accounts is not None:
            self.mirror_accounts(accounts, delete=True)
        if ledger is not None:
            self.mirror_ledger(ledger, delete=True)
        if price is not None:
            self.price_history = price
        if precision is not None:
            self.precision = precision
        if fx_adjustment is not None:
            self.fx_adjustment = fx_adjustment
````

**Comment by AlexTheWizardL** [comment]
Implemented when working on renaming for the pyLedger and CashCtrlLedger
