### ISSUE TITLE
Rename `base_currency` to `reporting_currency`

### ISSUE THREAD

**Issue by lasuk** [macxred/pyledger#5]
**Description**

'reporting_currency' appears to be the correct term to describe the currency, in which financial statements are reported. 
'base_currency' which is currently used in pyledger instead of 'reporting_currency' does nor appear to be commonly used in accounting.

<details><summary>See ChatGPT thread for details</summary>
<p>
**User:** In accounting, how is the currency called, in which the financial statement is denominated ?

**ChatGPT:** In accounting, the currency in which the financial statement is denominated is called the "functional currency" or "reporting currency." The functional currency is the primary currency of the economic environment in which an entity operates, whereas the reporting currency is the currency in which the financial statements are presented.

**User:** how about base currency?

**ChatGPT:** The term "base currency" is not typically used in accounting to refer to the currency in which the financial statements are denominated. Instead, "base currency" is more commonly used in the context of foreign exchange markets to refer to the first currency listed in a currency pair. For example, in the currency pair USD/EUR, USD is the base currency.

In accounting, the correct terms to refer to the currency in which financial statements are denominated are "functional currency" and "reporting currency." The functional currency is the primary currency of the primary economic environment in which the entity operates, while the reporting currency is the currency in which the financial statements are presented.

**User:** How about 'default currency'?

**ChatGPT:** The term "default currency" can be used in various contexts but is not a standard term in accounting. It often refers to the pre-set currency for a specific system or application, such as software, websites, or databases, where transactions or financial data might be recorded if no other currency is specified.

In accounting, the more precise terms are still "functional currency" and "reporting currency." The "functional currency" is the primary currency of the economic environment in which an entity operates, and the "reporting currency" is the currency in which the financial statements are presented.

The concept of "default currency" might be applied within a company's internal systems to simplify processes, but it is not a formal term used to describe the currency in which financial statements are denominated.
</p>
</details> 

**Action Items**
1. Rename the `base_currency` property to `reporting_currency` throughout `pyledger` and `cashctrl_ledger` packages.

**Comment by AlexTheWizardL** [comment]
Implemented when worked on renaming for packages
