### ISSUE TITLE
Create `MemoryLedger` class that stores accounting data as data frames in memory

### ISSUE THREAD

**Issue by lasuk** [macxred/pyledger#6]
**Description**

Create new `MemoryLedger` class that works as a non-persistent ledger system and stores accounting data as data frames in memory.  The class is particularly useful for demonstration and test purposes.

**Tasks:**
1. Implement `MemoryLedger` class that inherits from `StandaloneLedger`.
2. Create private properties to hold settings, including base currency and precision.
3. Create private properties to hold accounts, vat_codes, and ledger. At a later point, extend `MemoryLedger` to store price and fx_adjustment data frames.
4. Implement accessor and mutator methods for all aforementioned properties

**Comment by AlexTheWizardL** [comment]
### Proposed solution

1. Implement `MemoryLedger` class that inherits from `StandaloneLedger`.
    - Create new file that will contain new class with it's logic
   
2. Create private properties to hold `settings`, including `base currency` and `precision`.
    - Define a private property to store a `settings` object. Example:
    ```python
    SETTINGS = {
        "base_currency": "CHF",
        "precision": {
            "CAD": 0.01,
            "CHF": 0.01,
            "EUR": 0.01,
            "GBP": 0.01,
            "HKD": 0.01,
            "USD": 0.01,
        },
    }
    ```
    - Feed this property to the parent class. Example:
    ```python
        def __init__(self) -> None:
        """Initialize the MemoryLedger with hard-coded settings..."""
        super().__init__(
            settings=self.SETTINGS,
            ),
        )
    ```
    - Is this object enough for this step, or some more private properties should be created?
 
3. Create private properties to hold `accounts`, `vat_codes`, and `ledger`.
    - These properties are already defined at the `StandaloneLedger` class. I guess no need to redefine them. Correct?
    ```python
        class StandaloneLedger(LedgerEngine):
            _settings = None
            _account_chart = None
            _ledger = None
            _serialized_ledger = None
            _prices = None
            _vat_codes = None
            _fx_adjustments = None
    ```

4. Implement accessor and mutator methods for all aforementioned properties
    - Example for `ledger` entity. For accessors and mutators we need to have `ledger` as a `get` method, `add_ledger_entry` as a `put` method, and `delete_ledger_entry` as a `delete` method.
    - 
    - Here is example of those methods (pseudocode):
    ```python
        def ledger(self) -> pd.DataFrame:
            """Retrieves a DataFrame with all ledger transactions.

            Returns:
                pd.DataFrame: Combined DataFrame with ledger data.
            """
            return self._ledger

        def add_ledger_entry(self, entry: pd.DataFrame) -> int:
            """Add one or more entries to the general ledger."""
            automated_id = "id" not in df.columns
            df = self.standardize_ledger_columns(entry)

            # Ensure ID is not already in use
            duplicate = set(df["id"]).intersection(self._ledger["id"])
            if len(duplicate) > 0:
                # breakpoint()
                if automated_id:
                    # Replace ids by integers above the highest existing integer id
                    min_id = df["id"].astype(pd.Int64Dtype()).min(skipna=True)
                    max_id = self._ledger["id"].astype(pd.Int64Dtype()).max(skipna=True)
                    offset = max_id - min_id + 1
                    df["id"] = df["id"].astype(pd.Int64Dtype()) + offset
                    df["id"] = df["id"].astype(pd.StringDtype())
                else:
                    if len(duplicate) == 0:
                        message = f"Ledger id '{list(duplicate)[0]}' already used."
                    else:
                        message = f"Ledger ids {duplicate} already used."
                    raise ValueError(message)

            self._ledger = pd.concat([self._ledger, df], axis=0)

    ```

**Comment by AlexTheWizardL** [comment]
pytest tests inheritance for classes

**Comment by AlexTheWizardL** [comment]
### Further questions:

**General:** 
- How interface should look like? Like in the abstract `LedgerEngine` class or like all possible columns that are stored in the `constatns.py` folder?
- Should we make logical checks? Example: I can not create a vat_code with an account that isn`t in accounts DataFrame. I can not create a Vat code whose rate is greater than 10000. This question is related to all entities

**Vat_codes:**
- In the `cashctrl_ledger` we used the concept of `code` but in the pyledger, I see we use `id` instead. What should be used? We should align this since inheritance for tests won't work.
