### ISSUE TITLE
Cache `StandaloneLedger.serialized_ledger`

### ISSUE THREAD

**Issue by lasuk** [macxred/pyledger#70]
### Problem

Exporting a balance sheet to an Excel workbook currently takes over 10 minutes due to performance issues in the latest version of PyLedger. The process involves calling `LedgerEngine.account_balance()` in a loop, which indirectly invokes `complete_ledger()` on each iteration.

As part of the recent Project Rocket Launch changes, we removed caching for `StandaloneLedger.serialized_ledger()`. This method calls `complete_ledger()`, which generates automated ledger entries for tax and currency revaluation, a computationally intensive task. In the current implementation, each call to `account_balance()` triggers `complete_ledger()`, resulting in redundant computations with identical outputs.

### Temporary Fix 

A quick fix was applied in commit c680826 to the production branch, reintroducing caching for `StandaloneLedger.serialized_ledger()`. This reduced the Excel export time to less than one second.

While c680826 fixes the problem in my use case where data is not updated during run time, the current fix lacks a mechanism to invalidate the cache when the underlying accounting data changes, potentially leading to inconsistent or outdated results.

### Proposed Actions

1. Cache `StandaloneLedger.serialized_ledger()` to avoid redundant computations.
2. Cache Invalidation: Introduce a robust mechanism to invalidate caches whenever accounting data is modified. This may involve adding callbacks to storage entities to trigger cache invalidation.
3. Test that `StandaloneLedger.serialized_ledger()` is cached and the cache is properly invalidated. 

### Proposed Test Strategy

1. Populate a `MemoryLedger` instance with accounting data and call `serialized_ledger()`. 
2. Alter the internal data representation by bypassing the official mutator methods. Ensure that `serialized_ledger()` returns the same result as before, indicating that the cached data is returned.
3. Modify the data using the official mutator methods. Verify that `serialized_ledger()` now reflects both changes, confirming that the cache was invalidated and refreshed appropriately.

**Comment by AlexTheWizardL** [comment]
Implemented in #78
